services:
  postgres:
    image: postgres:16
    container_name: postgres-travel
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: travel
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d travel" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
